package com.example.demo.entity;

public class Assets {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column assets.assetsId
     *
     * @mbg.generated Wed Jun 13 10:19:49 CST 2018
     */
    private Integer assetsid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column assets.typeId
     *
     * @mbg.generated Wed Jun 13 10:19:49 CST 2018
     */
    private Integer typeid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column assets.assetsName
     *
     * @mbg.generated Wed Jun 13 10:19:49 CST 2018
     */
    private String assetsname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column assets.assetsCode
     *
     * @mbg.generated Wed Jun 13 10:19:49 CST 2018
     */
    private String assetscode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column assets.abbreviation
     *
     * @mbg.generated Wed Jun 13 10:19:49 CST 2018
     */
    private String abbreviation;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column assets.assetsKey
     *
     * @mbg.generated Wed Jun 13 10:19:49 CST 2018
     */
    private String assetskey;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column assets.assetsId
     *
     * @return the value of assets.assetsId
     *
     * @mbg.generated Wed Jun 13 10:19:49 CST 2018
     */
    public Integer getAssetsid() {
        return assetsid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column assets.assetsId
     *
     * @param assetsid the value for assets.assetsId
     *
     * @mbg.generated Wed Jun 13 10:19:49 CST 2018
     */
    public void setAssetsid(Integer assetsid) {
        this.assetsid = assetsid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column assets.typeId
     *
     * @return the value of assets.typeId
     *
     * @mbg.generated Wed Jun 13 10:19:49 CST 2018
     */
    public Integer getTypeid() {
        return typeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column assets.typeId
     *
     * @param typeid the value for assets.typeId
     *
     * @mbg.generated Wed Jun 13 10:19:49 CST 2018
     */
    public void setTypeid(Integer typeid) {
        this.typeid = typeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column assets.assetsName
     *
     * @return the value of assets.assetsName
     *
     * @mbg.generated Wed Jun 13 10:19:49 CST 2018
     */
    public String getAssetsname() {
        return assetsname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column assets.assetsName
     *
     * @param assetsname the value for assets.assetsName
     *
     * @mbg.generated Wed Jun 13 10:19:49 CST 2018
     */
    public void setAssetsname(String assetsname) {
        this.assetsname = assetsname == null ? null : assetsname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column assets.assetsCode
     *
     * @return the value of assets.assetsCode
     *
     * @mbg.generated Wed Jun 13 10:19:49 CST 2018
     */
    public String getAssetscode() {
        return assetscode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column assets.assetsCode
     *
     * @param assetscode the value for assets.assetsCode
     *
     * @mbg.generated Wed Jun 13 10:19:49 CST 2018
     */
    public void setAssetscode(String assetscode) {
        this.assetscode = assetscode == null ? null : assetscode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column assets.abbreviation
     *
     * @return the value of assets.abbreviation
     *
     * @mbg.generated Wed Jun 13 10:19:49 CST 2018
     */
    public String getAbbreviation() {
        return abbreviation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column assets.abbreviation
     *
     * @param abbreviation the value for assets.abbreviation
     *
     * @mbg.generated Wed Jun 13 10:19:49 CST 2018
     */
    public void setAbbreviation(String abbreviation) {
        this.abbreviation = abbreviation == null ? null : abbreviation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column assets.assetsKey
     *
     * @return the value of assets.assetsKey
     *
     * @mbg.generated Wed Jun 13 10:19:49 CST 2018
     */
    public String getAssetskey() {
        return assetskey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column assets.assetsKey
     *
     * @param assetskey the value for assets.assetsKey
     *
     * @mbg.generated Wed Jun 13 10:19:49 CST 2018
     */
    public void setAssetskey(String assetskey) {
        this.assetskey = assetskey == null ? null : assetskey.trim();
    }
}