package com.example.demo.entity;

public class Assetspermission {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column assetspermission.id
     *
     * @mbg.generated Wed Jun 13 10:19:49 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column assetspermission.permissionId
     *
     * @mbg.generated Wed Jun 13 10:19:49 CST 2018
     */
    private Integer permissionid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column assetspermission.assetsId
     *
     * @mbg.generated Wed Jun 13 10:19:49 CST 2018
     */
    private Integer assetsid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column assetspermission.id
     *
     * @return the value of assetspermission.id
     *
     * @mbg.generated Wed Jun 13 10:19:49 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column assetspermission.id
     *
     * @param id the value for assetspermission.id
     *
     * @mbg.generated Wed Jun 13 10:19:49 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column assetspermission.permissionId
     *
     * @return the value of assetspermission.permissionId
     *
     * @mbg.generated Wed Jun 13 10:19:49 CST 2018
     */
    public Integer getPermissionid() {
        return permissionid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column assetspermission.permissionId
     *
     * @param permissionid the value for assetspermission.permissionId
     *
     * @mbg.generated Wed Jun 13 10:19:49 CST 2018
     */
    public void setPermissionid(Integer permissionid) {
        this.permissionid = permissionid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column assetspermission.assetsId
     *
     * @return the value of assetspermission.assetsId
     *
     * @mbg.generated Wed Jun 13 10:19:49 CST 2018
     */
    public Integer getAssetsid() {
        return assetsid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column assetspermission.assetsId
     *
     * @param assetsid the value for assetspermission.assetsId
     *
     * @mbg.generated Wed Jun 13 10:19:49 CST 2018
     */
    public void setAssetsid(Integer assetsid) {
        this.assetsid = assetsid;
    }
}