package com.example.demo.entity;

public class Bankbatch {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bankbatch.id
     *
     * @mbg.generated Wed May 02 16:29:24 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bankbatch.bankId
     *
     * @mbg.generated Wed May 02 16:29:24 CST 2018
     */
    private Integer bankid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bankbatch.batch
     *
     * @mbg.generated Wed May 02 16:29:24 CST 2018
     */
    private Integer batch;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bankbatch.id
     *
     * @return the value of bankbatch.id
     *
     * @mbg.generated Wed May 02 16:29:24 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bankbatch.id
     *
     * @param id the value for bankbatch.id
     *
     * @mbg.generated Wed May 02 16:29:24 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bankbatch.bankId
     *
     * @return the value of bankbatch.bankId
     *
     * @mbg.generated Wed May 02 16:29:24 CST 2018
     */
    public Integer getBankid() {
        return bankid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bankbatch.bankId
     *
     * @param bankid the value for bankbatch.bankId
     *
     * @mbg.generated Wed May 02 16:29:24 CST 2018
     */
    public void setBankid(Integer bankid) {
        this.bankid = bankid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bankbatch.batch
     *
     * @return the value of bankbatch.batch
     *
     * @mbg.generated Wed May 02 16:29:24 CST 2018
     */
    public Integer getBatch() {
        return batch;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bankbatch.batch
     *
     * @param batch the value for bankbatch.batch
     *
     * @mbg.generated Wed May 02 16:29:24 CST 2018
     */
    public void setBatch(Integer batch) {
        this.batch = batch;
    }
}