package com.example.demo.entity;

import java.util.Date;

public class CiBatch {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ci_batch.batchid
     *
     * @mbg.generated Wed Jun 13 10:19:49 CST 2018
     */
    private Integer batchid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ci_batch.partnerId
     *
     * @mbg.generated Wed Jun 13 10:19:49 CST 2018
     */
    private Integer partnerid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ci_batch.assetsId
     *
     * @mbg.generated Wed Jun 13 10:19:49 CST 2018
     */
    private Integer assetsid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ci_batch.appBatchId
     *
     * @mbg.generated Wed Jun 13 10:19:49 CST 2018
     */
    private String appbatchid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ci_batch.addtime
     *
     * @mbg.generated Wed Jun 13 10:19:49 CST 2018
     */
    private Date addtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ci_batch.packingtime
     *
     * @mbg.generated Wed Jun 13 10:19:49 CST 2018
     */
    private Date packingtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ci_batch.ordercount
     *
     * @mbg.generated Wed Jun 13 10:19:49 CST 2018
     */
    private Integer ordercount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ci_batch.assetsstatus
     *
     * @mbg.generated Wed Jun 13 10:19:49 CST 2018
     */
    private Integer assetsstatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ci_batch.binsuredpremium
     *
     * @mbg.generated Wed Jun 13 10:19:49 CST 2018
     */
    private Float binsuredpremium;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ci_batch.firstterm
     *
     * @mbg.generated Wed Jun 13 10:19:49 CST 2018
     */
    private Float firstterm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ci_batch.tenterms
     *
     * @mbg.generated Wed Jun 13 10:19:49 CST 2018
     */
    private Float tenterms;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ci_batch.lastterm
     *
     * @mbg.generated Wed Jun 13 10:19:49 CST 2018
     */
    private Float lastterm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ci_batch.cautionmoney
     *
     * @mbg.generated Wed Jun 13 10:19:49 CST 2018
     */
    private Float cautionmoney;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ci_batch.batchid
     *
     * @return the value of ci_batch.batchid
     *
     * @mbg.generated Wed Jun 13 10:19:49 CST 2018
     */
    public Integer getBatchid() {
        return batchid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ci_batch.batchid
     *
     * @param batchid the value for ci_batch.batchid
     *
     * @mbg.generated Wed Jun 13 10:19:49 CST 2018
     */
    public void setBatchid(Integer batchid) {
        this.batchid = batchid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ci_batch.partnerId
     *
     * @return the value of ci_batch.partnerId
     *
     * @mbg.generated Wed Jun 13 10:19:49 CST 2018
     */
    public Integer getPartnerid() {
        return partnerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ci_batch.partnerId
     *
     * @param partnerid the value for ci_batch.partnerId
     *
     * @mbg.generated Wed Jun 13 10:19:49 CST 2018
     */
    public void setPartnerid(Integer partnerid) {
        this.partnerid = partnerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ci_batch.assetsId
     *
     * @return the value of ci_batch.assetsId
     *
     * @mbg.generated Wed Jun 13 10:19:49 CST 2018
     */
    public Integer getAssetsid() {
        return assetsid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ci_batch.assetsId
     *
     * @param assetsid the value for ci_batch.assetsId
     *
     * @mbg.generated Wed Jun 13 10:19:49 CST 2018
     */
    public void setAssetsid(Integer assetsid) {
        this.assetsid = assetsid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ci_batch.appBatchId
     *
     * @return the value of ci_batch.appBatchId
     *
     * @mbg.generated Wed Jun 13 10:19:49 CST 2018
     */
    public String getAppbatchid() {
        return appbatchid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ci_batch.appBatchId
     *
     * @param appbatchid the value for ci_batch.appBatchId
     *
     * @mbg.generated Wed Jun 13 10:19:49 CST 2018
     */
    public void setAppbatchid(String appbatchid) {
        this.appbatchid = appbatchid == null ? null : appbatchid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ci_batch.addtime
     *
     * @return the value of ci_batch.addtime
     *
     * @mbg.generated Wed Jun 13 10:19:49 CST 2018
     */
    public Date getAddtime() {
        return addtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ci_batch.addtime
     *
     * @param addtime the value for ci_batch.addtime
     *
     * @mbg.generated Wed Jun 13 10:19:49 CST 2018
     */
    public void setAddtime(Date addtime) {
        this.addtime = addtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ci_batch.packingtime
     *
     * @return the value of ci_batch.packingtime
     *
     * @mbg.generated Wed Jun 13 10:19:49 CST 2018
     */
    public Date getPackingtime() {
        return packingtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ci_batch.packingtime
     *
     * @param packingtime the value for ci_batch.packingtime
     *
     * @mbg.generated Wed Jun 13 10:19:49 CST 2018
     */
    public void setPackingtime(Date packingtime) {
        this.packingtime = packingtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ci_batch.ordercount
     *
     * @return the value of ci_batch.ordercount
     *
     * @mbg.generated Wed Jun 13 10:19:49 CST 2018
     */
    public Integer getOrdercount() {
        return ordercount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ci_batch.ordercount
     *
     * @param ordercount the value for ci_batch.ordercount
     *
     * @mbg.generated Wed Jun 13 10:19:49 CST 2018
     */
    public void setOrdercount(Integer ordercount) {
        this.ordercount = ordercount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ci_batch.assetsstatus
     *
     * @return the value of ci_batch.assetsstatus
     *
     * @mbg.generated Wed Jun 13 10:19:49 CST 2018
     */
    public Integer getAssetsstatus() {
        return assetsstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ci_batch.assetsstatus
     *
     * @param assetsstatus the value for ci_batch.assetsstatus
     *
     * @mbg.generated Wed Jun 13 10:19:49 CST 2018
     */
    public void setAssetsstatus(Integer assetsstatus) {
        this.assetsstatus = assetsstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ci_batch.binsuredpremium
     *
     * @return the value of ci_batch.binsuredpremium
     *
     * @mbg.generated Wed Jun 13 10:19:49 CST 2018
     */
    public Float getBinsuredpremium() {
        return binsuredpremium;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ci_batch.binsuredpremium
     *
     * @param binsuredpremium the value for ci_batch.binsuredpremium
     *
     * @mbg.generated Wed Jun 13 10:19:49 CST 2018
     */
    public void setBinsuredpremium(Float binsuredpremium) {
        this.binsuredpremium = binsuredpremium;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ci_batch.firstterm
     *
     * @return the value of ci_batch.firstterm
     *
     * @mbg.generated Wed Jun 13 10:19:49 CST 2018
     */
    public Float getFirstterm() {
        return firstterm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ci_batch.firstterm
     *
     * @param firstterm the value for ci_batch.firstterm
     *
     * @mbg.generated Wed Jun 13 10:19:49 CST 2018
     */
    public void setFirstterm(Float firstterm) {
        this.firstterm = firstterm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ci_batch.tenterms
     *
     * @return the value of ci_batch.tenterms
     *
     * @mbg.generated Wed Jun 13 10:19:49 CST 2018
     */
    public Float getTenterms() {
        return tenterms;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ci_batch.tenterms
     *
     * @param tenterms the value for ci_batch.tenterms
     *
     * @mbg.generated Wed Jun 13 10:19:49 CST 2018
     */
    public void setTenterms(Float tenterms) {
        this.tenterms = tenterms;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ci_batch.lastterm
     *
     * @return the value of ci_batch.lastterm
     *
     * @mbg.generated Wed Jun 13 10:19:49 CST 2018
     */
    public Float getLastterm() {
        return lastterm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ci_batch.lastterm
     *
     * @param lastterm the value for ci_batch.lastterm
     *
     * @mbg.generated Wed Jun 13 10:19:49 CST 2018
     */
    public void setLastterm(Float lastterm) {
        this.lastterm = lastterm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ci_batch.cautionmoney
     *
     * @return the value of ci_batch.cautionmoney
     *
     * @mbg.generated Wed Jun 13 10:19:49 CST 2018
     */
    public Float getCautionmoney() {
        return cautionmoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ci_batch.cautionmoney
     *
     * @param cautionmoney the value for ci_batch.cautionmoney
     *
     * @mbg.generated Wed Jun 13 10:19:49 CST 2018
     */
    public void setCautionmoney(Float cautionmoney) {
        this.cautionmoney = cautionmoney;
    }
}