package com.example.demo.entity;

public class ClOrderstatus {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cl_orderstatus.statusId
     *
     * @mbg.generated Fri Jul 13 10:25:43 CST 2018
     */
    private Integer statusid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cl_orderstatus.statusDescribe
     *
     * @mbg.generated Fri Jul 13 10:25:43 CST 2018
     */
    private String statusdescribe;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cl_orderstatus.statusId
     *
     * @return the value of cl_orderstatus.statusId
     *
     * @mbg.generated Fri Jul 13 10:25:43 CST 2018
     */
    public Integer getStatusid() {
        return statusid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cl_orderstatus.statusId
     *
     * @param statusid the value for cl_orderstatus.statusId
     *
     * @mbg.generated Fri Jul 13 10:25:43 CST 2018
     */
    public void setStatusid(Integer statusid) {
        this.statusid = statusid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cl_orderstatus.statusDescribe
     *
     * @return the value of cl_orderstatus.statusDescribe
     *
     * @mbg.generated Fri Jul 13 10:25:43 CST 2018
     */
    public String getStatusdescribe() {
        return statusdescribe;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cl_orderstatus.statusDescribe
     *
     * @param statusdescribe the value for cl_orderstatus.statusDescribe
     *
     * @mbg.generated Fri Jul 13 10:25:43 CST 2018
     */
    public void setStatusdescribe(String statusdescribe) {
        this.statusdescribe = statusdescribe == null ? null : statusdescribe.trim();
    }
}