package com.example.demo.entity;

public class ClOrderbase {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cl_orderbase.proId
     *
     * @mbg.generated Tue Jul 10 10:57:29 CST 2018
     */
    private Integer proid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cl_orderbase.objectId
     *
     * @mbg.generated Tue Jul 10 10:57:29 CST 2018
     */
    private String objectid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cl_orderbase.statusId
     *
     * @mbg.generated Tue Jul 10 10:57:29 CST 2018
     */
    private Integer statusid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cl_orderbase.custName
     *
     * @mbg.generated Tue Jul 10 10:57:29 CST 2018
     */
    private String custname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cl_orderbase.idCardType
     *
     * @mbg.generated Tue Jul 10 10:57:29 CST 2018
     */
    private String idcardtype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cl_orderbase.idCardNo
     *
     * @mbg.generated Tue Jul 10 10:57:29 CST 2018
     */
    private String idcardno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cl_orderbase.leaseTerm
     *
     * @mbg.generated Tue Jul 10 10:57:29 CST 2018
     */
    private Integer leaseterm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cl_orderbase.leasePeriod
     *
     * @mbg.generated Tue Jul 10 10:57:29 CST 2018
     */
    private Integer leaseperiod;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cl_orderbase.leaseTopric
     *
     * @mbg.generated Tue Jul 10 10:57:29 CST 2018
     */
    private Float leasetopric;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cl_orderbase.loanMoney
     *
     * @mbg.generated Tue Jul 10 10:57:29 CST 2018
     */
    private Float loanmoney;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cl_orderbase.createTime
     *
     * @mbg.generated Tue Jul 10 10:57:29 CST 2018
     */
    private String createtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cl_orderbase.createPeople
     *
     * @mbg.generated Tue Jul 10 10:57:29 CST 2018
     */
    private Integer createpeople;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cl_orderbase.updateTime
     *
     * @mbg.generated Tue Jul 10 10:57:29 CST 2018
     */
    private String updatetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cl_orderbase.updatePeople
     *
     * @mbg.generated Tue Jul 10 10:57:29 CST 2018
     */
    private Integer updatepeople;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cl_orderbase.proId
     *
     * @return the value of cl_orderbase.proId
     *
     * @mbg.generated Tue Jul 10 10:57:29 CST 2018
     */
    public Integer getProid() {
        return proid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cl_orderbase.proId
     *
     * @param proid the value for cl_orderbase.proId
     *
     * @mbg.generated Tue Jul 10 10:57:29 CST 2018
     */
    public void setProid(Integer proid) {
        this.proid = proid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cl_orderbase.objectId
     *
     * @return the value of cl_orderbase.objectId
     *
     * @mbg.generated Tue Jul 10 10:57:29 CST 2018
     */
    public String getObjectid() {
        return objectid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cl_orderbase.objectId
     *
     * @param objectid the value for cl_orderbase.objectId
     *
     * @mbg.generated Tue Jul 10 10:57:29 CST 2018
     */
    public void setObjectid(String objectid) {
        this.objectid = objectid == null ? null : objectid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cl_orderbase.statusId
     *
     * @return the value of cl_orderbase.statusId
     *
     * @mbg.generated Tue Jul 10 10:57:29 CST 2018
     */
    public Integer getStatusid() {
        return statusid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cl_orderbase.statusId
     *
     * @param statusid the value for cl_orderbase.statusId
     *
     * @mbg.generated Tue Jul 10 10:57:29 CST 2018
     */
    public void setStatusid(Integer statusid) {
        this.statusid = statusid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cl_orderbase.custName
     *
     * @return the value of cl_orderbase.custName
     *
     * @mbg.generated Tue Jul 10 10:57:29 CST 2018
     */
    public String getCustname() {
        return custname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cl_orderbase.custName
     *
     * @param custname the value for cl_orderbase.custName
     *
     * @mbg.generated Tue Jul 10 10:57:29 CST 2018
     */
    public void setCustname(String custname) {
        this.custname = custname == null ? null : custname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cl_orderbase.idCardType
     *
     * @return the value of cl_orderbase.idCardType
     *
     * @mbg.generated Tue Jul 10 10:57:29 CST 2018
     */
    public String getIdcardtype() {
        return idcardtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cl_orderbase.idCardType
     *
     * @param idcardtype the value for cl_orderbase.idCardType
     *
     * @mbg.generated Tue Jul 10 10:57:29 CST 2018
     */
    public void setIdcardtype(String idcardtype) {
        this.idcardtype = idcardtype == null ? null : idcardtype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cl_orderbase.idCardNo
     *
     * @return the value of cl_orderbase.idCardNo
     *
     * @mbg.generated Tue Jul 10 10:57:29 CST 2018
     */
    public String getIdcardno() {
        return idcardno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cl_orderbase.idCardNo
     *
     * @param idcardno the value for cl_orderbase.idCardNo
     *
     * @mbg.generated Tue Jul 10 10:57:29 CST 2018
     */
    public void setIdcardno(String idcardno) {
        this.idcardno = idcardno == null ? null : idcardno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cl_orderbase.leaseTerm
     *
     * @return the value of cl_orderbase.leaseTerm
     *
     * @mbg.generated Tue Jul 10 10:57:29 CST 2018
     */
    public Integer getLeaseterm() {
        return leaseterm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cl_orderbase.leaseTerm
     *
     * @param leaseterm the value for cl_orderbase.leaseTerm
     *
     * @mbg.generated Tue Jul 10 10:57:29 CST 2018
     */
    public void setLeaseterm(Integer leaseterm) {
        this.leaseterm = leaseterm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cl_orderbase.leasePeriod
     *
     * @return the value of cl_orderbase.leasePeriod
     *
     * @mbg.generated Tue Jul 10 10:57:29 CST 2018
     */
    public Integer getLeaseperiod() {
        return leaseperiod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cl_orderbase.leasePeriod
     *
     * @param leaseperiod the value for cl_orderbase.leasePeriod
     *
     * @mbg.generated Tue Jul 10 10:57:29 CST 2018
     */
    public void setLeaseperiod(Integer leaseperiod) {
        this.leaseperiod = leaseperiod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cl_orderbase.leaseTopric
     *
     * @return the value of cl_orderbase.leaseTopric
     *
     * @mbg.generated Tue Jul 10 10:57:29 CST 2018
     */
    public Float getLeasetopric() {
        return leasetopric;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cl_orderbase.leaseTopric
     *
     * @param leasetopric the value for cl_orderbase.leaseTopric
     *
     * @mbg.generated Tue Jul 10 10:57:29 CST 2018
     */
    public void setLeasetopric(Float leasetopric) {
        this.leasetopric = leasetopric;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cl_orderbase.loanMoney
     *
     * @return the value of cl_orderbase.loanMoney
     *
     * @mbg.generated Tue Jul 10 10:57:29 CST 2018
     */
    public Float getLoanmoney() {
        return loanmoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cl_orderbase.loanMoney
     *
     * @param loanmoney the value for cl_orderbase.loanMoney
     *
     * @mbg.generated Tue Jul 10 10:57:29 CST 2018
     */
    public void setLoanmoney(Float loanmoney) {
        this.loanmoney = loanmoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cl_orderbase.createTime
     *
     * @return the value of cl_orderbase.createTime
     *
     * @mbg.generated Tue Jul 10 10:57:29 CST 2018
     */
    public String getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cl_orderbase.createTime
     *
     * @param createtime the value for cl_orderbase.createTime
     *
     * @mbg.generated Tue Jul 10 10:57:29 CST 2018
     */
    public void setCreatetime(String createtime) {
        this.createtime = createtime == null ? null : createtime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cl_orderbase.createPeople
     *
     * @return the value of cl_orderbase.createPeople
     *
     * @mbg.generated Tue Jul 10 10:57:29 CST 2018
     */
    public Integer getCreatepeople() {
        return createpeople;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cl_orderbase.createPeople
     *
     * @param createpeople the value for cl_orderbase.createPeople
     *
     * @mbg.generated Tue Jul 10 10:57:29 CST 2018
     */
    public void setCreatepeople(Integer createpeople) {
        this.createpeople = createpeople;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cl_orderbase.updateTime
     *
     * @return the value of cl_orderbase.updateTime
     *
     * @mbg.generated Tue Jul 10 10:57:29 CST 2018
     */
    public String getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cl_orderbase.updateTime
     *
     * @param updatetime the value for cl_orderbase.updateTime
     *
     * @mbg.generated Tue Jul 10 10:57:29 CST 2018
     */
    public void setUpdatetime(String updatetime) {
        this.updatetime = updatetime == null ? null : updatetime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cl_orderbase.updatePeople
     *
     * @return the value of cl_orderbase.updatePeople
     *
     * @mbg.generated Tue Jul 10 10:57:29 CST 2018
     */
    public Integer getUpdatepeople() {
        return updatepeople;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cl_orderbase.updatePeople
     *
     * @param updatepeople the value for cl_orderbase.updatePeople
     *
     * @mbg.generated Tue Jul 10 10:57:29 CST 2018
     */
    public void setUpdatepeople(Integer updatepeople) {
        this.updatepeople = updatepeople;
    }
}