package com.example.demo.entity;

public class Partnerpermission {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column partnerpermission.id
     *
     * @mbg.generated Wed Jun 13 08:57:01 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column partnerpermission.partnerId
     *
     * @mbg.generated Wed Jun 13 08:57:01 CST 2018
     */
    private Integer partnerid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column partnerpermission.permissionId
     *
     * @mbg.generated Wed Jun 13 08:57:01 CST 2018
     */
    private Integer permissionid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column partnerpermission.id
     *
     * @return the value of partnerpermission.id
     *
     * @mbg.generated Wed Jun 13 08:57:01 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column partnerpermission.id
     *
     * @param id the value for partnerpermission.id
     *
     * @mbg.generated Wed Jun 13 08:57:01 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column partnerpermission.partnerId
     *
     * @return the value of partnerpermission.partnerId
     *
     * @mbg.generated Wed Jun 13 08:57:01 CST 2018
     */
    public Integer getPartnerid() {
        return partnerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column partnerpermission.partnerId
     *
     * @param partnerid the value for partnerpermission.partnerId
     *
     * @mbg.generated Wed Jun 13 08:57:01 CST 2018
     */
    public void setPartnerid(Integer partnerid) {
        this.partnerid = partnerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column partnerpermission.permissionId
     *
     * @return the value of partnerpermission.permissionId
     *
     * @mbg.generated Wed Jun 13 08:57:01 CST 2018
     */
    public Integer getPermissionid() {
        return permissionid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column partnerpermission.permissionId
     *
     * @param permissionid the value for partnerpermission.permissionId
     *
     * @mbg.generated Wed Jun 13 08:57:01 CST 2018
     */
    public void setPermissionid(Integer permissionid) {
        this.permissionid = permissionid;
    }
}