package com.example.demo.entity;

public class Partnerfile {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column partnerfile.fileid
     *
     * @mbg.generated Tue Jul 03 14:58:55 CST 2018
     */
    private Integer fileid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column partnerfile.typeid
     *
     * @mbg.generated Tue Jul 03 14:58:55 CST 2018
     */
    private Integer typeid;
    
	private String typename;
    private String uploadusername;
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column partnerfile.fatherid
     *
     * @mbg.generated Tue Jul 03 14:58:55 CST 2018
     */
    private Integer fatherid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column partnerfile.filename
     *
     * @mbg.generated Tue Jul 03 14:58:55 CST 2018
     */
    private String filename;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column partnerfile.abbreviation
     *
     * @mbg.generated Tue Jul 03 14:58:55 CST 2018
     */
    private String abbreviation;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column partnerfile.permission
     *
     * @mbg.generated Tue Jul 03 14:58:55 CST 2018
     */
    private String permission;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column partnerfile.uploaduser
     *
     * @mbg.generated Tue Jul 03 14:58:55 CST 2018
     */
    private Integer uploaduser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column partnerfile.saveposition
     *
     * @mbg.generated Tue Jul 03 14:58:55 CST 2018
     */
    private String saveposition;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column partnerfile.updatetime
     *
     * @mbg.generated Tue Jul 03 14:58:55 CST 2018
     */
    private String updatetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column partnerfile.size
     *
     * @mbg.generated Tue Jul 03 14:58:55 CST 2018
     */
    private Integer size;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column partnerfile.fileid
     *
     * @return the value of partnerfile.fileid
     *
     * @mbg.generated Tue Jul 03 14:58:55 CST 2018
     */
    public Integer getFileid() {
        return fileid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column partnerfile.fileid
     *
     * @param fileid the value for partnerfile.fileid
     *
     * @mbg.generated Tue Jul 03 14:58:55 CST 2018
     */
    public void setFileid(Integer fileid) {
        this.fileid = fileid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column partnerfile.typeid
     *
     * @return the value of partnerfile.typeid
     *
     * @mbg.generated Tue Jul 03 14:58:55 CST 2018
     */
    public Integer getTypeid() {
        return typeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column partnerfile.typeid
     *
     * @param typeid the value for partnerfile.typeid
     *
     * @mbg.generated Tue Jul 03 14:58:55 CST 2018
     */
    public void setTypeid(Integer typeid) {
        this.typeid = typeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column partnerfile.fatherid
     *
     * @return the value of partnerfile.fatherid
     *
     * @mbg.generated Tue Jul 03 14:58:55 CST 2018
     */
    public Integer getFatherid() {
        return fatherid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column partnerfile.fatherid
     *
     * @param fatherid the value for partnerfile.fatherid
     *
     * @mbg.generated Tue Jul 03 14:58:55 CST 2018
     */
    public void setFatherid(Integer fatherid) {
        this.fatherid = fatherid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column partnerfile.filename
     *
     * @return the value of partnerfile.filename
     *
     * @mbg.generated Tue Jul 03 14:58:55 CST 2018
     */
    public String getFilename() {
        return filename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column partnerfile.filename
     *
     * @param filename the value for partnerfile.filename
     *
     * @mbg.generated Tue Jul 03 14:58:55 CST 2018
     */
    public void setFilename(String filename) {
        this.filename = filename == null ? null : filename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column partnerfile.abbreviation
     *
     * @return the value of partnerfile.abbreviation
     *
     * @mbg.generated Tue Jul 03 14:58:55 CST 2018
     */
    public String getAbbreviation() {
        return abbreviation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column partnerfile.abbreviation
     *
     * @param abbreviation the value for partnerfile.abbreviation
     *
     * @mbg.generated Tue Jul 03 14:58:55 CST 2018
     */
    public void setAbbreviation(String abbreviation) {
        this.abbreviation = abbreviation == null ? null : abbreviation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column partnerfile.permission
     *
     * @return the value of partnerfile.permission
     *
     * @mbg.generated Tue Jul 03 14:58:55 CST 2018
     */
    public String getPermission() {
        return permission;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column partnerfile.permission
     *
     * @param permission the value for partnerfile.permission
     *
     * @mbg.generated Tue Jul 03 14:58:55 CST 2018
     */
    public void setPermission(String permission) {
        this.permission = permission == null ? null : permission.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column partnerfile.uploaduser
     *
     * @return the value of partnerfile.uploaduser
     *
     * @mbg.generated Tue Jul 03 14:58:55 CST 2018
     */
    public Integer getUploaduser() {
        return uploaduser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column partnerfile.uploaduser
     *
     * @param uploaduser the value for partnerfile.uploaduser
     *
     * @mbg.generated Tue Jul 03 14:58:55 CST 2018
     */
    public void setUploaduser(Integer uploaduser) {
        this.uploaduser = uploaduser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column partnerfile.saveposition
     *
     * @return the value of partnerfile.saveposition
     *
     * @mbg.generated Tue Jul 03 14:58:55 CST 2018
     */
    public String getSaveposition() {
        return saveposition;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column partnerfile.saveposition
     *
     * @param saveposition the value for partnerfile.saveposition
     *
     * @mbg.generated Tue Jul 03 14:58:55 CST 2018
     */
    public void setSaveposition(String saveposition) {
        this.saveposition = saveposition == null ? null : saveposition.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column partnerfile.updatetime
     *
     * @return the value of partnerfile.updatetime
     *
     * @mbg.generated Tue Jul 03 14:58:55 CST 2018
     */
    public String getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column partnerfile.updatetime
     *
     * @param updatetime the value for partnerfile.updatetime
     *
     * @mbg.generated Tue Jul 03 14:58:55 CST 2018
     */
    public void setUpdatetime(String updatetime) {
        this.updatetime = updatetime == null ? null : updatetime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column partnerfile.size
     *
     * @return the value of partnerfile.size
     *
     * @mbg.generated Tue Jul 03 14:58:55 CST 2018
     */
    public Integer getSize() {
        return size;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column partnerfile.size
     *
     * @param size the value for partnerfile.size
     *
     * @mbg.generated Tue Jul 03 14:58:55 CST 2018
     */
    public void setSize(Integer size) {
        this.size = size;
    }
    
    public String getTypename() {
		return typename;
	}

	public void setTypename(String typename) {
		this.typename = typename;
	}

	public String getUploadusername() {
		return uploadusername;
	}

	public void setUploadusername(String uploadusername) {
		this.uploadusername = uploadusername;
	}

}