package com.example.demo.entity;

public class Partner {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column partner.partnerId
     *
     * @mbg.generated Tue Jun 12 16:59:45 CST 2018
     */
    private Integer partnerid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column partner.typeId
     *
     * @mbg.generated Tue Jun 12 16:59:45 CST 2018
     */
    private Integer typeid;
    private String typename;


	/**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column partner.name
     *
     * @mbg.generated Tue Jun 12 16:59:45 CST 2018
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column partner.abbreviation
     *
     * @mbg.generated Tue Jun 12 16:59:45 CST 2018
     */
    private String abbreviation;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column partner.partnerCode
     *
     * @mbg.generated Tue Jun 12 16:59:45 CST 2018
     */
    private String partnercode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column partner.partnerKey
     *
     * @mbg.generated Tue Jun 12 16:59:45 CST 2018
     */
    private String partnerkey;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column partner.partnerId
     *
     * @return the value of partner.partnerId
     *
     * @mbg.generated Tue Jun 12 16:59:45 CST 2018
     */
    public Integer getPartnerid() {
        return partnerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column partner.partnerId
     *
     * @param partnerid the value for partner.partnerId
     *
     * @mbg.generated Tue Jun 12 16:59:45 CST 2018
     */
    public void setPartnerid(Integer partnerid) {
        this.partnerid = partnerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column partner.typeId
     *
     * @return the value of partner.typeId
     *
     * @mbg.generated Tue Jun 12 16:59:45 CST 2018
     */
    public Integer getTypeid() {
        return typeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column partner.typeId
     *
     * @param typeid the value for partner.typeId
     *
     * @mbg.generated Tue Jun 12 16:59:45 CST 2018
     */
    public void setTypeid(Integer typeid) {
        this.typeid = typeid;
    }
    
    public String getTypename() {
		return typename;
	}

	public void setTypename(String typename) {
		this.typename = typename == null ? null : typename.trim();
	}
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column partner.name
     *
     * @return the value of partner.name
     *
     * @mbg.generated Tue Jun 12 16:59:45 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column partner.name
     *
     * @param name the value for partner.name
     *
     * @mbg.generated Tue Jun 12 16:59:45 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column partner.abbreviation
     *
     * @return the value of partner.abbreviation
     *
     * @mbg.generated Tue Jun 12 16:59:45 CST 2018
     */
    public String getAbbreviation() {
        return abbreviation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column partner.abbreviation
     *
     * @param abbreviation the value for partner.abbreviation
     *
     * @mbg.generated Tue Jun 12 16:59:45 CST 2018
     */
    public void setAbbreviation(String abbreviation) {
        this.abbreviation = abbreviation == null ? null : abbreviation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column partner.partnerCode
     *
     * @return the value of partner.partnerCode
     *
     * @mbg.generated Tue Jun 12 16:59:45 CST 2018
     */
    public String getPartnercode() {
        return partnercode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column partner.partnerCode
     *
     * @param partnercode the value for partner.partnerCode
     *
     * @mbg.generated Tue Jun 12 16:59:45 CST 2018
     */
    public void setPartnercode(String partnercode) {
        this.partnercode = partnercode == null ? null : partnercode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column partner.partnerKey
     *
     * @return the value of partner.partnerKey
     *
     * @mbg.generated Tue Jun 12 16:59:45 CST 2018
     */
    public String getPartnerkey() {
        return partnerkey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column partner.partnerKey
     *
     * @param partnerkey the value for partner.partnerKey
     *
     * @mbg.generated Tue Jun 12 16:59:45 CST 2018
     */
    public void setPartnerkey(String partnerkey) {
        this.partnerkey = partnerkey == null ? null : partnerkey.trim();
    }
}