package com.example.demo.entity;

public class Permissiontype {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column permissiontype.typeId
     *
     * @mbg.generated Wed Jun 13 08:48:43 CST 2018
     */
    private Integer typeid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column permissiontype.typeName
     *
     * @mbg.generated Wed Jun 13 08:48:43 CST 2018
     */
    private String typename;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column permissiontype.typeId
     *
     * @return the value of permissiontype.typeId
     *
     * @mbg.generated Wed Jun 13 08:48:43 CST 2018
     */
    public Integer getTypeid() {
        return typeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column permissiontype.typeId
     *
     * @param typeid the value for permissiontype.typeId
     *
     * @mbg.generated Wed Jun 13 08:48:43 CST 2018
     */
    public void setTypeid(Integer typeid) {
        this.typeid = typeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column permissiontype.typeName
     *
     * @return the value of permissiontype.typeName
     *
     * @mbg.generated Wed Jun 13 08:48:43 CST 2018
     */
    public String getTypename() {
        return typename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column permissiontype.typeName
     *
     * @param typename the value for permissiontype.typeName
     *
     * @mbg.generated Wed Jun 13 08:48:43 CST 2018
     */
    public void setTypename(String typename) {
        this.typename = typename == null ? null : typename.trim();
    }
}