package com.example.demo.entity;

import java.util.List;

public class Stuser {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stuser.id
     *
     * @mbg.generated Wed May 02 16:10:08 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stuser.name
     *
     * @mbg.generated Wed May 02 16:10:08 CST 2018
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stuser.password
     *
     * @mbg.generated Wed May 02 16:10:08 CST 2018
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stuser.logintime
     *
     * @mbg.generated Wed May 02 16:10:08 CST 2018
     */
    private Integer logintime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stuser.bankid
     *
     * @mbg.generated Wed May 02 16:10:08 CST 2018
     */
    private Integer bankid;
    
    private List<Integer>  batchs;

    public List<Integer> getBatchs() {
		return batchs;
	}

	public void setBatchs(List<Integer> batchs) {
		this.batchs = batchs;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stuser.id
     *
     * @return the value of stuser.id
     *
     * @mbg.generated Wed May 02 16:10:08 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stuser.id
     *
     * @param id the value for stuser.id
     *
     * @mbg.generated Wed May 02 16:10:08 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stuser.name
     *
     * @return the value of stuser.name
     *
     * @mbg.generated Wed May 02 16:10:08 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stuser.name
     *
     * @param name the value for stuser.name
     *
     * @mbg.generated Wed May 02 16:10:08 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stuser.password
     *
     * @return the value of stuser.password
     *
     * @mbg.generated Wed May 02 16:10:08 CST 2018
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stuser.password
     *
     * @param password the value for stuser.password
     *
     * @mbg.generated Wed May 02 16:10:08 CST 2018
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stuser.logintime
     *
     * @return the value of stuser.logintime
     *
     * @mbg.generated Wed May 02 16:10:08 CST 2018
     */
    public Integer getLogintime() {
        return logintime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stuser.logintime
     *
     * @param logintime the value for stuser.logintime
     *
     * @mbg.generated Wed May 02 16:10:08 CST 2018
     */
    public void setLogintime(Integer logintime) {
        this.logintime = logintime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stuser.bankid
     *
     * @return the value of stuser.bankid
     *
     * @mbg.generated Wed May 02 16:10:08 CST 2018
     */
    public Integer getBankid() {
        return bankid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stuser.bankid
     *
     * @param bankid the value for stuser.bankid
     *
     * @mbg.generated Wed May 02 16:10:08 CST 2018
     */
    public void setBankid(Integer bankid) {
        this.bankid = bankid;
    }
}