package com.example.demo.mapper;

import com.example.demo.entity.Assetstype;

public interface AssetstypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table assetstype
     *
     * @mbg.generated Wed Jun 13 10:19:49 CST 2018
     */
    int deleteByPrimaryKey(Integer typeid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table assetstype
     *
     * @mbg.generated Wed Jun 13 10:19:49 CST 2018
     */
    int insert(Assetstype record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table assetstype
     *
     * @mbg.generated Wed Jun 13 10:19:49 CST 2018
     */
    int insertSelective(Assetstype record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table assetstype
     *
     * @mbg.generated Wed Jun 13 10:19:49 CST 2018
     */
    Assetstype selectByPrimaryKey(Integer typeid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table assetstype
     *
     * @mbg.generated Wed Jun 13 10:19:49 CST 2018
     */
    int updateByPrimaryKeySelective(Assetstype record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table assetstype
     *
     * @mbg.generated Wed Jun 13 10:19:49 CST 2018
     */
    int updateByPrimaryKey(Assetstype record);
}