package com.example.demo.mapper;

import com.example.demo.entity.Assets;

public interface AssetsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table assets
     *
     * @mbg.generated Wed Jun 13 10:19:49 CST 2018
     */
    int deleteByPrimaryKey(Integer assetsid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table assets
     *
     * @mbg.generated Wed Jun 13 10:19:49 CST 2018
     */
    int insert(Assets record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table assets
     *
     * @mbg.generated Wed Jun 13 10:19:49 CST 2018
     */
    int insertSelective(Assets record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table assets
     *
     * @mbg.generated Wed Jun 13 10:19:49 CST 2018
     */
    Assets selectByPrimaryKey(Integer assetsid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table assets
     *
     * @mbg.generated Wed Jun 13 10:19:49 CST 2018
     */
    int updateByPrimaryKeySelective(Assets record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table assets
     *
     * @mbg.generated Wed Jun 13 10:19:49 CST 2018
     */
    int updateByPrimaryKey(Assets record);
}