package com.example.demo.mapper;

import com.example.demo.entity.Assetspermission;

public interface AssetspermissionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table assetspermission
     *
     * @mbg.generated Wed Jun 13 10:19:49 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table assetspermission
     *
     * @mbg.generated Wed Jun 13 10:19:49 CST 2018
     */
    int insert(Assetspermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table assetspermission
     *
     * @mbg.generated Wed Jun 13 10:19:49 CST 2018
     */
    int insertSelective(Assetspermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table assetspermission
     *
     * @mbg.generated Wed Jun 13 10:19:49 CST 2018
     */
    Assetspermission selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table assetspermission
     *
     * @mbg.generated Wed Jun 13 10:19:49 CST 2018
     */
    int updateByPrimaryKeySelective(Assetspermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table assetspermission
     *
     * @mbg.generated Wed Jun 13 10:19:49 CST 2018
     */
    int updateByPrimaryKey(Assetspermission record);
}