package com.example.demo.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.example.demo.entity.CiBatch;

public interface CiBatchMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ci_batch
     *
     * @mbg.generated Wed Jun 13 10:19:49 CST 2018
     */
    int deleteByPrimaryKey(Integer batchid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ci_batch
     *
     * @mbg.generated Wed Jun 13 10:19:49 CST 2018
     */
    int insert(CiBatch record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ci_batch
     *
     * @mbg.generated Wed Jun 13 10:19:49 CST 2018
     */
    int insertSelective(CiBatch record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ci_batch
     *
     * @mbg.generated Wed Jun 13 10:19:49 CST 2018
     */
    CiBatch selectByPrimaryKey(Integer batchid);
    //������ѯ
    List<CiBatch> selectBatchSelective(CiBatch record);
    //������ѯ ��ҳ����
    List<CiBatch> selectBatchSelectivePaging(@Param("record")CiBatch record,@Param("start")Integer start,@Param("size")Integer size);
    //������ѯ ҳ������
    int selectBatchCountSelective(CiBatch record);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ci_batch
     *
     * @mbg.generated Wed Jun 13 10:19:49 CST 2018
     */
    int updateByPrimaryKeySelective(CiBatch record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ci_batch
     *
     * @mbg.generated Wed Jun 13 10:19:49 CST 2018
     */
    int updateByPrimaryKey(CiBatch record);
}