package com.example.demo.mapper;

import java.util.List;

import com.example.demo.entity.ClAssetapplyresult;

public interface ClAssetapplyresultMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_assetapplyresult
     *
     * @mbg.generated Fri Jul 13 10:18:19 CST 2018
     */
    int insert(ClAssetapplyresult record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_assetapplyresult
     *
     * @mbg.generated Fri Jul 13 10:18:19 CST 2018
     */
    int insertSelective(ClAssetapplyresult record);
    
    List<ClAssetapplyresult> selectResultByProId(int proid);
    
}