package com.example.demo.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.example.demo.entity.CiBatch;
import com.example.demo.entity.ClOrderbase;

public interface ClOrderbaseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_orderbase
     *
     * @mbg.generated Tue Jul 10 10:41:11 CST 2018
     */
    int deleteByPrimaryKey(Integer proid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_orderbase
     *
     * @mbg.generated Tue Jul 10 10:41:11 CST 2018
     */
    int insert(ClOrderbase record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_orderbase
     *
     * @mbg.generated Tue Jul 10 10:41:11 CST 2018
     */
    int insertSelective(ClOrderbase record);
    int insertSelectiveReturnId(ClOrderbase record);



    List<ClOrderbase> selectSelective(ClOrderbase orderbase);
    List<ClOrderbase> selectSelectivePaging(@Param("record")ClOrderbase record,@Param("start")Integer start,@Param("size")Integer size);
    int selectCountSelective(ClOrderbase record);    
    
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_orderbase
     *
     * @mbg.generated Tue Jul 10 10:41:11 CST 2018
     */
    ClOrderbase selectByPrimaryKey(Integer proid);


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_orderbase
     *
     * @mbg.generated Tue Jul 10 10:41:11 CST 2018
     */
    int updateByPrimaryKeySelective(ClOrderbase record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_orderbase
     *
     * @mbg.generated Tue Jul 10 10:41:11 CST 2018
     */
    int updateByPrimaryKey(ClOrderbase record);
}