package com.example.demo.mapper;

import org.apache.ibatis.annotations.Mapper;

import com.example.demo.entity.Partner;

@Mapper
public interface PartnerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table partner
     *
     * @mbg.generated Tue Jun 12 16:59:45 CST 2018
     */
    int deleteByPrimaryKey(Integer partnerid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table partner
     *
     * @mbg.generated Tue Jun 12 16:59:45 CST 2018
     */
    int insert(Partner record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table partner
     *
     * @mbg.generated Tue Jun 12 16:59:45 CST 2018
     */
    int insertSelective(Partner record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table partner
     *
     * @mbg.generated Tue Jun 12 16:59:45 CST 2018
     */
    Partner selectByPrimaryKey(Integer partnerid);
    Partner selectByUniqueKey(String partnercode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table partner
     *
     * @mbg.generated Tue Jun 12 16:59:45 CST 2018
     */
    int updateByPrimaryKeySelective(Partner record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table partner
     *
     * @mbg.generated Tue Jun 12 16:59:45 CST 2018
     */
    int updateByPrimaryKey(Partner record);
}