package com.example.demo.mapper;

import org.apache.ibatis.annotations.Param;

import com.example.demo.entity.Partnerpermission;

public interface PartnerpermissionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table partnerpermission
     *
     * @mbg.generated Wed Jun 13 08:57:01 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table partnerpermission
     *
     * @mbg.generated Wed Jun 13 08:57:01 CST 2018
     */
    int insert(Partnerpermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table partnerpermission
     *
     * @mbg.generated Wed Jun 13 08:57:01 CST 2018
     */
    int insertSelective(Partnerpermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table partnerpermission
     *
     * @mbg.generated Wed Jun 13 08:57:01 CST 2018
     */
    Partnerpermission selectByPrimaryKey(Integer id);
    
    
    Partnerpermission selectByUniqueKey(@Param("partnerId")Integer partnerId,@Param("peimissionId")Integer peimissionId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table partnerpermission
     *
     * @mbg.generated Wed Jun 13 08:57:01 CST 2018
     */
    int updateByPrimaryKeySelective(Partnerpermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table partnerpermission
     *
     * @mbg.generated Wed Jun 13 08:57:01 CST 2018
     */
    int updateByPrimaryKey(Partnerpermission record);
}