package com.example.demo.mapper;

import com.example.demo.entity.Partnertype;

public interface PartnertypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table partnertype
     *
     * @mbg.generated Tue Jun 12 16:59:45 CST 2018
     */
    int deleteByPrimaryKey(Integer typeid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table partnertype
     *
     * @mbg.generated Tue Jun 12 16:59:45 CST 2018
     */
    int insert(Partnertype record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table partnertype
     *
     * @mbg.generated Tue Jun 12 16:59:45 CST 2018
     */
    int insertSelective(Partnertype record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table partnertype
     *
     * @mbg.generated Tue Jun 12 16:59:45 CST 2018
     */
    Partnertype selectByPrimaryKey(Integer typeid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table partnertype
     *
     * @mbg.generated Tue Jun 12 16:59:45 CST 2018
     */
    int updateByPrimaryKeySelective(Partnertype record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table partnertype
     *
     * @mbg.generated Tue Jun 12 16:59:45 CST 2018
     */
    int updateByPrimaryKey(Partnertype record);
}