package com.example.demo.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import com.example.demo.entity.Partner;
import com.example.demo.entity.Partnertype;

@Mapper
public interface PartnerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table partner
     *
     * @mbg.generated Tue Jun 12 16:59:45 CST 2018
     */
    int deleteByPrimaryKey(Integer partnerid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table partner
     *
     * @mbg.generated Tue Jun 12 16:59:45 CST 2018
     */
    int insert(Partner record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table partner
     *
     * @mbg.generated Tue Jun 12 16:59:45 CST 2018
     */
    int insertSelective(Partner record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table partner
     *
     * @mbg.generated Tue Jun 12 16:59:45 CST 2018
     */
    int selectMainUser(Integer partnerid);
    Partner selectByPrimaryKey(Integer partnerid);
    Partner selectByUniqueKey(String partnercode);
    
    List<Partner> selectSelectivePaging(@Param("record")Partner record,@Param("search")String search,@Param("start")Integer start,@Param("size")Integer size);
    int selectCountSelective(@Param("record")Partner record,@Param("search")String search);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table partner
     *
     * @mbg.generated Tue Jun 12 16:59:45 CST 2018
     */
    int updateByPrimaryKeySelective(Partner record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table partner
     *
     * @mbg.generated Tue Jun 12 16:59:45 CST 2018
     */
    int updateByPrimaryKey(Partner record);
}