package com.example.demo.mapper;

import com.example.demo.entity.Permission;

public interface PermissionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table permission
     *
     * @mbg.generated Wed Jun 13 08:48:43 CST 2018
     */
    int deleteByPrimaryKey(Integer permissionid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table permission
     *
     * @mbg.generated Wed Jun 13 08:48:43 CST 2018
     */
    int insert(Permission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table permission
     *
     * @mbg.generated Wed Jun 13 08:48:43 CST 2018
     */
    int insertSelective(Permission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table permission
     *
     * @mbg.generated Wed Jun 13 08:48:43 CST 2018
     */
    Permission selectByPrimaryKey(Integer permissionid);
    
    Permission selectByUniqueCode(String permissionCode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table permission
     *
     * @mbg.generated Wed Jun 13 08:48:43 CST 2018
     */
    int updateByPrimaryKeySelective(Permission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table permission
     *
     * @mbg.generated Wed Jun 13 08:48:43 CST 2018
     */
    int updateByPrimaryKey(Permission record);
}