package com.example.demo.mapper;

import java.util.Set;

import org.apache.ibatis.annotations.Param;

import com.example.demo.entity.Stuser;



public interface StuserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stuser
     *
     * @mbg.generated Tue Apr 03 09:28:30 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stuser
     *
     * @mbg.generated Tue Apr 03 09:28:30 CST 2018
     */
    int insert(Stuser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stuser
     *
     * @mbg.generated Tue Apr 03 09:28:30 CST 2018
     */
    int insertSelective(Stuser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stuser
     *
     * @mbg.generated Tue Apr 03 09:28:30 CST 2018
     */
    Stuser selectByPrimaryKey(Integer id);
    Stuser selectByNamePassword(@Param("name")String name,@Param("password")String password);
    
	public Stuser getByUsername(String username);  
	  
    public Set<String> getRoles(String username);  
  
    public Set<String> getPermissions(String username);
    
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stuser
     *
     * @mbg.generated Tue Apr 03 09:28:30 CST 2018
     */
    int updateByPrimaryKeySelective(Stuser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stuser
     *
     * @mbg.generated Tue Apr 03 09:28:30 CST 2018
     */
    int updateByPrimaryKey(Stuser record);
}